---
image: docker:20.10.21-dind-alpine3.16

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - apk add --no-cache
    python3 python3-dev py3-pip gcc git curl build-base
    autoconf automake py3-cryptography linux-headers
    musl-dev libffi-dev openssl-dev openssh rsync
  - rsync --version
  - docker info
  - python3 --version
  - python3 -m pip install -I ansible molecule[docker] ansible-lint pytest pytest-testinfra
  - ansible --version
  - molecule --version

molecule:
  stage: test
  script:
    - molecule test
  tags:
    - docker