---
# tasks file for docker_ansible_role
- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ docker_prerequisites_packages }}"
  become: true

- name: Add directory for keyring file
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0777
  become: true

- name: Add Dockers official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present
  become: true

- name: Add Dockers repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true
  become: true

- name: Install Docker main packages
  ansible.builtin.apt:
    name:
      - "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ docker_main_packages }}"
  become: true

- name: Ensure docker service is started and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Add users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    group: docker
  become: true
  with_items: "{{ docker_users }}"