---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu2004
    image: ubuntu:20.04
    privileged: true
provisioner:
  name: ansible
verifier:
  name: testinfra
  options:
    verbose: true