---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu2004
    image: ubuntu:20.04
    privileged: true
provisioner:
  name: ansible
verifier:
  name: testinfra
  options:
    verbose: true
lint: |
  set -e
  yamllint .
  ansible-lint -c .config/ansible-lint.yml
scenario:
  test_sequence:
    - destroy
    - lint
    - create
    - converge
    - verify